### ISSUE TITLE
Test schlägt (mit gleichem Code) manchmal fehl, manchmal nicht.

### ISSUE THREAD

**Issue by AdrianAulbach** [grueneschweiz/weblingservice#18]
Der RevisionRepositoryTest schlägt teilweise fehl, obwohl er kurz zuvor wie auch etwas später wieder funktioniert.
Z.B. bei den Travis-Builds #139&#140, bei #140 klappte es dann (alle drei Builds mit dem gleichen Code (Commit 111a750)).
Wurde noch nicht schlau draus, wann und warum es auftritt. Kann es dran liegen, dass wir gegen die Webling-Test-Instanz testen (wäre ev. ein Problem, wenn der Test mehrmals gleichzeitig ausgeführt wird).
https://github.com/grueneschweiz/weblingservice/blob/d11191c5fef40142fe219d5ad46b76e4c8968b26/tests/Unit/Repository/Revision/RevisionRepositoryTest.php#L39

**Comment by cyrillbolliger** [comment]
Ist mir auch aufgefallen... schaue ich an.

**Comment by AdrianAulbach** [comment]
:+1:
